Web/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using AutoMapper;

using Core.Data.Dto;
using Core.Filters;
using Core.Services;
using Core.Services.Business;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Web.ViewModels;

namespace Web.Controllers.Mvc {
    [Authorize]
    [ParameterizedLogAction("Person action invoked")]
    public class PersonController: BaseController<PersonController> {
        private readonly IPersonBusinessManager _personBusinessManager;

        public PersonController(ILogger<PersonController> logger, IMapper mapper,
            IPersonBusinessManager personBusinessManager) : base(logger, mapper) {
            _personBusinessManager = personBusinessManager;
        }

        public IActionResult Index() {
            return View();
        }
    }
}

namespace Web.Controllers.Api {
    [Route("api/[controller]")]
    [ApiController]
    [LogAction]
    public class PersonController: ControllerBase {
        private readonly IMapper _mapper;
        private readonly IViewRenderService _viewRenderService;
        private readonly IPersonBusinessManager _personBusinessManager;
        public PersonController(
            IMapper mapper,
            IViewRenderService viewRenderService,
            //ISectionBusinessManager businessManager,
            IPersonBusinessManager personBusinessManager) {
            _mapper = mapper;
            _viewRenderService = viewRenderService;
            _personBusinessManager = personBusinessManager;
        }

        [HttpGet("GetPersons", Name = "GetPersons")]
        public async Task<PagerDto<PersonListViewModel>> GetPersons([FromQuery] PagerFilterViewModel model) {
            var result = await _personBusinessManager.GetPersonPager(_mapper.Map<PagerFilterDto>(model));
            var pager = new PagerDto<PersonListViewModel>(_mapper.Map<List<PersonListViewModel>>(result.Data), result.RecordsTotal, result.Start, result.PageSize);
            return pager;
        }

        [HttpGet("DetailsPerson", Name = "DetailsPerson")]
        public async Task<IActionResult> DetailsPerson([FromQuery] Guid id) {
            var item = await _personBusinessManager.GetPerson(id);
            if(item == null)
                return NotFound();

            var html = await _viewRenderService.RenderToStringAsync("_DetailsPartial", _mapper.Map<PersonViewModel>(item));
            return Ok(html);
        }

        [HttpGet("AddPerson", Name = "AddPerson")]
        public async Task<IActionResult> AddPerson() {
            var html = await _viewRenderService.RenderToStringAsync("_CreatePartial", new PersonViewModel());
            return Ok(html);
        }

        [HttpPost("CreatePerson", Name = "CreatePerson")]
        public async Task<IActionResult> CreatePerson([FromBody] PersonViewModel model) {
            if(ModelState.IsValid) {
                var item = await _personBusinessManager.CreatePerson(_mapper.Map<PersonDto>(model));
                if(item == null)
                    return BadRequest();
                return Ok(_mapper.Map<PersonViewModel>(item));
            }
            return BadRequest();
        }

        [HttpGet("EditPerson", Name = "EditPerson")]
        public async Task<IActionResult> EditPerson([FromQuery] Guid id) {
            var item = await _personBusinessManager.GetPerson(id);
            if(item == null)
                return NotFound();

            var html = await _viewRenderService.RenderToStringAsync("_EditPartial", _mapper.Map<PersonViewModel>(item));
            return Ok(html);
        }

        [HttpPut("UpdatePerson", Name = "UpdatePerson")]
        public async Task<IActionResult> UpdatePerson([FromQuery] Guid id, [FromBody] PersonViewModel model) {
            if(ModelState.IsValid) {
                var item = await _personBusinessManager.UpdatePerson(id, _mapper.Map<PersonDto>(model));
                if(item == null)
                    return BadRequest();
                return Ok(_mapper.Map<PersonViewModel>(item));
            }
            return BadRequest();
        }

        [HttpGet("DeletePersons", Name = "DeletePersons")]
        public async Task<IActionResult> DeletePersons([FromQuery] Guid[] id) {
            if(id.Length > 0) {
                var result = await _personBusinessManager.DeletePersons(id);
                if(result)
                    return Ok(id);
            }
            return BadRequest("No items selected");
        }
    }
}

Web/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using AutoMapper;

using Core.Data.Dto;
using Core.Extension;
using Core.Filters;
using Core.Services;
using Core.Services.Business;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Logging;

using Web.ViewModels;

namespace Web.Controllers.Mvc {
    [Authorize]
    [LogAction]
    public class TodoController: BaseController<TodoController> {
        public TodoController(ILogger<TodoController> logger, IMapper mapper) : base(logger, mapper) { }

        public IActionResult Index() {
            return View(new TodoFilterViewModel());
        }
    }
}

namespace Web.Controllers.Api {
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    [LogAction]
    public class TodoController: ControllerBase {
        private readonly IMapper _mapper;
        private readonly IViewRenderService _viewRenderService;

        private readonly ITodoBusinessManager _todoBusinessManager;
        private readonly IAccountBusinessManager _accountBusinessService;

        public TodoController(IMapper mapper,
            IViewRenderService viewRenderService,
            ITodoBusinessManager todoBusinessManager,
            IAccountBusinessManager accountBusinessService) {
            _mapper = mapper;
            _viewRenderService = viewRenderService;
            _todoBusinessManager = todoBusinessManager;
            _accountBusinessService = accountBusinessService;
        }

        [HttpGet("GetTodoList", Name = "GetTodoList")]
        public async Task<PagerDto<TodoListViewModel>> GetTodoList([FromQuery] TodoFilterViewModel model) {
            var result = await _todoBusinessManager.GetTodoPage(_mapper.Map<TodoFilterDto>(model, opts =>
                opts.AfterMap((_, dest) => { var dto = dest as TodoFilterDto; dto.UserId = User.GetUserId(); dto.UserLogin = User.FindFirstValue(ClaimTypes.Name); })));
            var pager = new PagerDto<TodoListViewModel>(_mapper.Map<List<TodoListViewModel>>(result.Data), result.RecordsTotal, result.Start, result.PageSize);
            return pager;
        }

        [HttpGet("DeleteTodoList", Name = "DeleteTodoList")]
        public async Task<ActionResult> DeleteTodoList([FromQuery] Guid[] id) {
            if(id.Length > 0) {
                var result = await _todoBusinessManager.DeleteTodo(id);
                if(result)
                    return Ok(id);
            }
            return BadRequest("No items selected");
        }

        [HttpGet("DetailsTodo", Name = "DetailsTodo")]
        public async Task<IActionResult> DetailsTodo([FromQuery] Guid id) {
            var item = await _todoBusinessManager.GetTodo(id);
            if(item == null)
                return NotFound();

            var html = await _viewRenderService.RenderToStringAsync("_DetailsPartial", _mapper.Map<TodoListViewModel>(item));

            return Ok(html);
        }

        [HttpGet("AddTodo", Name = "AddTodo")]
        public async Task<IActionResult> AddTodo() {
            var curUserId = User.GetUserId();
            var users = await _accountBusinessService.GetUsersWithoutObservers();
            var viewData = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary()) {
                { "IsCreating", true },
                { "Users", users.Select(x=> new SelectListItem(x.UserName, x.Id, x.Id == curUserId)) }
            };

            var html = await _viewRenderService.RenderToStringAsync("_CreateUpdatePartial", new TodoViewModel(), viewData);
            return Ok(html);
        }

        [HttpPost("CreateTodo", Name = "CreateTodo")]
        public async Task<IActionResult> CreateTodo([FromBody] TodoViewModel model) {
            try {
                if(!ModelState.IsValid) {
                    throw new Exception("Form is not valid!");
                }
                var item = await _todoBusinessManager.CreateTodo(_mapper.Map<TodoDto>(model));
                if(item == null)
                    throw new Exception("No records have been created! Please, fill the required fields!");

                return Ok(_mapper.Map<TodoViewModel>(item));
            } catch(Exception e) {
                return BadRequest(e.Message ?? e.StackTrace);
            }
        }

        [HttpGet("EditTodo", Name = "EditTodo")]
        public async Task<IActionResult> EditTodo([FromQuery] Guid id) {
            var item = await _todoBusinessManager.GetTodo(id);
            if(item == null)
                return NotFound();

            var users = await _accountBusinessService.GetUsersWithoutObservers();
            var viewData = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary()) {
                { "IsCreating", false },
                { "UserId", User.GetUserId() },
                { "Users", users.Select(x=> new SelectListItem(x.UserName, x.Id)) }
            };

            var html = await _viewRenderService.RenderToStringAsync("_CreateUpdatePartial", _mapper.Map<TodoViewModel>(item), viewData);
            return Ok(html);
        }

        [HttpPost("UpdateTodo", Name = "UpdateTodo")]
        public async Task<IActionResult> UpdateTodo([FromQuery] Guid id, [FromBody] TodoViewModel model) {
            try {
                if(!ModelState.IsValid) {
                    throw new Exception("Form is not valid!");
                }
                var dto = _mapper.Map<TodoDto>(model);

                var item = await _todoBusinessManager.UpdateTodo(id, dto);
                if(item == null)
                    throw new Exception("No records have been updated! Please, fill the required fields!");

                return Ok(_mapper.Map<TodoViewModel>(item));
            } catch(Exception e) {
                return BadRequest(e.Message ?? e.StackTrace);
            }
        }

        [HttpPut("UpdateStatus", Name = "UpdateStatus")]
        public async Task<IActionResult> UpdateStatus([FromQuery] Guid id) {
            try {
                var dto = await _todoBusinessManager.GetTodo(id);
                dto.IsCompleted = !dto.IsCompleted;

                var item = await _todoBusinessManager.UpdateTodo(id, dto);
                if(item == null)
                    throw new Exception("No records have been updated! Please, fill the required fields!");

                return Ok(_mapper.Map<TodoViewModel>(item));
            } catch(Exception e) {
                return BadRequest(e.Message ?? e.StackTrace);
            }
        }
    }
}

Web/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Margo Assistant</title>

    <partial name="_StylePartial" />
    <style>
        body > .grid {
            height: 100%;
        }

        .image {
            margin-top: -100px;
        }

        .column {
            max-width: 450px;
        }
    </style>
</head>
<body>
    <div class="ui middle aligned center aligned grid">
        @RenderBody()
    </div>

    <partial name="_ScriptPartial" />
    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_FooterPartial.cshtml
<div class="ui bottom inverted overlay segment sidebar overlay visible">
    <div class="ui container">
        <div class="ui inverted nine item labeled icon menu " style="">
            <a class="item">
                <i class="home icon"></i>
                Home
            </a>
            <a class="item">
                <i class="block layout icon"></i>
                Topics
            </a>
            <a class="item">
                <i class="smile icon"></i>
                Friends
            </a>
            <a class="item">
                <i class="calendar icon"></i>
                History
            </a>
            <a class="item">
                <i class="mail icon"></i>
                Messages
            </a>
            <a class="item">
                <i class="chat icon"></i>
                Discussions
            </a>
            <a class="item">
                <i class="trophy icon"></i>
                Achievements
            </a>
            <a class="item">
                <i class="shop icon"></i>
                Store
            </a>
            <a class="item">
                <i class="settings icon"></i>
                Settings
            </a>
        </div>
    </div>
</div>

Web/Views/Shared/_HeaderPartial.cshtml
@{
    var url = Context.Request.Path.ToString();
    var crumbs = url.Equals("/") ? new string[] { "" } : url.Split('/');

    var userName = ViewData["UserName"];

    var tableId = Guid.NewGuid();
}

<div class="ui two stackable column grid m-0 border-b-1">
    <div class="row">
        <div class="twelve wide column px-1">
            <div class="ui flex align-center">
                <span id="sidebar-btn" style="cursor: pointer; margin-right: 5px;"><i class="inverted brown list icon"></i></span>
                <div class="ui header" style="margin-top: 0;">@ViewData["Title"]</div>
            </div>
            <div class="ui secondary  menu">
                <div class="header item">
                    <div class="ui breadcrumb">
                        @foreach(var crumb in crumbs) {
                            if(string.IsNullOrEmpty(crumb)) {
                                <a class="section" asp-controller="Home" asp-action="Index"><i class="home icon"></i> Home</a>
                            } else {
                                <div class="divider"> / </div>
                                <a class="section" asp-controller="@crumb" asp-action="Index">@crumb</a>
                            }
                        }
                    </div>
                </div>
                <div class="right item">
                    <div class="ui simple dropdown">
                        @userName <i class="dropdown icon"></i>
                        <div class="menu">
                            <div class="header">Header Item</div>
                            <a class="item" href="#">Link Item</a>
                            <a class="item" href="#">Link Item</a>
                            <div class="divider"></div>
                            <a class="item" href="javascript:void(0);" onclick="$('#@tableId').submit();"><i class="sign-out icon"></i> Signout</a>
                            <form id="@tableId" asp-controller="Account" asp-action="Logout"></form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="four wide column"></div>
    </div>
</div>

Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Core.Data.Entities

@inject SignInManager<AspNetUserEntity> SignInManager
@inject UserManager<AspNetUserEntity> UserManager

@{
    var userName = UserManager.GetUserName(User);
    ViewData["UserName"] = userName;

    var isSignIn = SignInManager.IsSignedIn(User);
    ViewData["IsSignIn"] = isSignIn;

    //var roles = await UserManager.GetRolesAsync(User.R);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Margo Assistant</title>

    <partial name="_StylePartial" />
</head>


<body id="mainbody">
    <div id="sidenav" class="sidenav">
        <partial name="_SidebarPartial" />
    </div>
    <div id="main-content" class="main-content">
        <partial name="_HeaderPartial" model="userName" />

        <div class="ui two stackable column divided grid m-0">
            <div class="mobile-wide twelve wide column p-1">
                @RenderBody()
            </div>
            <div class="four wide column p-1 right-side mobile-hidden">
                @RenderSection("RightSidebar", required: false)
            </div>
        </div>
    </div>

    <partial name="_ScriptPartial" />
    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_ModalPartial.cshtml
<div class="modal fade" id="modalBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent"></div>
            <div class="modal-footer d-flex justify-content-between">
                <button id="modalSubmitRemoveBtn" type="submit" class="btn btn-danger" form="submitModalRemoveForm" onclick="if (!confirm('Are you sure want to delete this?')) { return false; }" hidden><i class="material-icons mr-1">delete_outline</i> Remove</button>
                &nbsp;
                <div>
                    <button id="modalCloseBtn" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="modalSubmitBtn" type="submit" class="btn btn-primary" form="submitModalFrom" hidden>Save</button>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Shared/_RightSidebarPartial.cshtml
<div class="ui right vertical menu">
    <a class="item">Features</a>
    <a class="item">Testimonials</a>
    <a class="item">Sign-in</a>
</div>

Web/Views/Shared/_ScriptPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-serializeJSON/jquery.serializejson.min.js"></script>
    <script src="~/lib/jquery-loadjson/dist/jquery.loadJSON.min.js"></script>
    <script src="~/lib/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation/additional-methods.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/jquery-datatables-se/js/dataTables.semanticui.min.js"></script>
    <script src="~/lib/jquery-fancytree/dist/jquery.fancytree-all-deps.min.js"></script>
    <script src="~/lib/sortablejs/Sortable.min.js"></script>
    <script src="~/lib/jquery-sortablejs/jquery-sortable.min.js"></script>

    @*<script src="~/lib/moment/moment.min.js"></script>*@
    @*<script src="~/lib/semantic/semantic.min.js"></script>*@
    <script src="~/lib/fomantic-ui/semantic.min.js"></script>
    <script src="~/lib/aspnet-signalr/signalr.min.js"></script>

    <script src="~/js/jquery-extensions.js"></script>
    <script src="~/js/notification-hub.js"></script>
    <script src="~/js/document-controller.js"></script>
    <script src="~/js/treeview-controller.js"></script>
    <script src="~/js/api-controller.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/serializer-extensions.js"></script>
</environment>

<environment exclude="Development">
    <script src="~/js/vendor.min.js"></script>
    <script src="~/js/site.min.js"></script>
    <script src="~/js/notification-hub.js"></script>
</environment>

Web/Views/Shared/_SidebarPartial.cshtml
@{
    var url = Context.Request.Path.ToString().ToLower();
}

<!-- Sidebar Menu -->
<div class="ui vertical inverted menu">
    <div class="item">
        <a class="ui logo icon image" href="#">
            <img src="~/images/margo-icon.png">
        </a>
        <a href="/"><b>Margo Assistant</b></a>
    </div>

    <div class="item">
        <div class="header">Dashboard</div>
        <div class="menu">
            <a class="item @(url.Contains("/home") || url.Equals("/") ? "active" : "")" asp-controller="Home" asp-action="Index">Home</a>
            <a class="item @(url.Contains("/todo") ? "active" : "")" asp-controller="Todo" asp-action="Index">To Do</a>
        </div>
    </div>

    <div class="item">
        <div class="header">Database</div>
        <div class="menu">
            <a class="item @(url.Contains("/person") ? "active" : "")" asp-controller="Person" asp-action="Index">Persons</a>
            <a class="item @(url.Contains("/company") ? "active" : "")" asp-controller="Company" asp-action="Index">Companies</a>
            <a class="item @(url.Contains("/uccount") ? "active" : "")" asp-controller="Uccount" asp-action="Index">Accounts</a>
        </div>
    </div>

    <div class="item">
        <div class="header">Payment</div>
        <div class="menu">
            <a class="item @(url.Contains("/invoice") ? "active" : "")" asp-controller="Invoice" asp-action="Index">Invoices</a>
            <a class="item @(url.Contains("/payment") ? "active" : "")" asp-controller="Payment" asp-action="Index">Payments</a>
        </div>
    </div>

    @if(User.IsInRole("Administrator")) {
    <div class="item">
        <div class="header">Admin settings</div>
        <div class="menu">
           
            <a class="item @(url.Contains("/category") ? "active" : "")" asp-controller="Category" asp-action="Index">
                Categories
            </a>
            @*<a class="item @(url.Contains("/section") ? "active" : "")" asp-controller="Section" asp-action="Index">
                Section
            </a>*@
            <a class="item @(url.Contains("/vendor") ? "active" : "")" asp-controller="Vendor" asp-action="Index">
                Vendors
            </a>
        </div>

        <div class="header">Accounts</div>
        <div class="menu">
            <a class="item @(url.Equals("/account") ? "active" : "") " asp-controller="Account" asp-action="Index">
                Users
            </a>
            <a class="item @(url.Contains("/account/request") ? "active" : "") " asp-controller="Account" asp-action="Request">
                Requests
            </a>
            <a class="item @(url.Contains("/account/activity") ? "active" : "") " asp-controller="Account" asp-action="Activity">
                Activity
            </a>
        </div>
    </div>
    }
</div>

Web/Views/Shared/_StylePartial.cshtml
<environment include="Development">
    <link rel="stylesheet" href="~/lib/fomantic-ui/semantic.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-datatables-se/css/dataTables.semanticui.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-fancytree/dist/skin-lion/ui.fancytree.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</environment>

<environment exclude="Development">
    <link rel="stylesheet" href="~/css/vendor.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
</environment>