Web/ViewModels/Company/CompanyDataListViewModel.cs
using System;
using System.Collections.Generic;

namespace Web.ViewModels {
    public class CompanyDataListViewModel {
        public Guid CompanyId { get; set; }
        public List<CompanyDataViewModel> Data { get; set; }
    }
}

Web/ViewModels/Company/CompanyDataMenuItemViewModel.cs
using System;

namespace Web.ViewModels {
    public class CompanyDataMenuItemViewModel {
        public Guid Id { get; set; }
        public string Value { get; set; }
        public bool Selected { get; set; }
        public Guid[] Ids { get; set; }
    }
}

Web/ViewModels/Company/CompanyDataMenuListViewModel.cs
using System;
using System.Collections.Generic;

namespace Web.ViewModels {
    public class CompanyDataMenuListViewModel {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public List<CompanyDataMenuItemViewModel> Fields { get; set; }
    }
}

Web/ViewModels/Company/CompanyDataViewModel.cs
using System;

namespace Web.ViewModels {
    public class CompanyDataViewModel {
        public Guid Id { get; set; }
        public Guid CompanyId { get; set; }
        public Guid FieldId { get; set; }
        public Guid ServiceId { get; set; }

        public string ServiceName { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}

Web/ViewModels/Company/CompanyFilterViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels {
    public class CompanyFilterViewModel: PagerFilterViewModel {
        [Display(Name = "CEO")]
        public Guid? CEOId { get; set; }
    }
}

Web/ViewModels/Company/CompanyListViewModel.cs
using System;

namespace Web.ViewModels {
    public class CompanyListViewModel {
        public Guid Id { get; set; }

        public string CEOName { get; set; }

        public string IsStarred { get; set; }

        public string Name { get; set; }

        public DateTime? Founded { get; set; }
        public string EIN { get; set; }
        public string DB { get; set; }

        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}

Web/ViewModels/Company/CompanySectionFieldViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

using Core.Data.Enums;
using Core.Extension;

using Web.Utils;

namespace Web.ViewModels {
    public class CompanySectionFieldViewModel {
        public Guid Id { get; set; }
        [Required]
        [MaxLength(24)]
        public string Name { get; set; }
        [Required]
        [MaxLength(256)]
        public string Value { get; set; } = "";
        public FieldEnum Type { get; set; }
        public string TypeName => Type.GetAttribute<DisplayAttribute>().Name.ToLower();
        public string HTMLTypeName => Type.GetHTMLType();
        public bool IsRequired { get; set; }
        public int Sort { get; set; }
        public bool IsHidden { get; set; }
    }
}

Web/ViewModels/Company/CompanySectionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels {
    public class CompanySectionViewModel {
        public Guid Id { get; set; }
        [Display(Name = "Company")]
        public Guid? CompanyId { get; set; }
        [MaxLength(64)]
        public string Name { get; set; }
        public IEnumerable<CompanySectionFieldViewModel> Fields { get; set; }
    }
}

Web/ViewModels/Company/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels {
    public class CompanyViewModel {
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "CEO")]
        public Guid CEOId { get; set; }

        [Required]
        [MaxLength(256)]
        [Display(Name = "Business Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Founded")]
        [DataType(DataType.Date)]
        public DateTime Founded { get; set; }

        [Required]
        [MaxLength(60)]
        [Display(Name = "EIN")]
        public string EIN { get; set; }

        [Required]
        [MaxLength(60)]
        [Display(Name = "D&B")]
        public string DB { get; set; }

        [MaxLength(2048)]
        public string Description { get; set; }

        public IEnumerable<CompanySectionViewModel> Sections { get; set; }
        public IEnumerable<CompanyDataViewModel> Data { get; set; }

        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}

Web/Controllers/UccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using AutoMapper;

using Core.Data.Dto;
using Core.Data.Enums;
using Core.Extension;
using Core.Filters;
using Core.Services;
using Core.Services.Business;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Logging;

using Web.ViewModels;

namespace Web.Controllers.Mvc {
    [Authorize]
    [LogAction]
    public class UccountController: BaseController<UccountController> {
        private readonly IUccountBusinessManager _uccountBusinessManager;
        private readonly IPersonBusinessManager _personBusinessManager;
        private readonly ICompanyBusinessManager _companyBusinessManager;
        private readonly IVendorBusinessManager _vendorBusinessManager;
        private readonly ICategoryBusinessManager _categoryBusinessManager;
        public UccountController(ILogger<UccountController> logger, IMapper mapper,
            IUccountBusinessManager uccountBusinessManager,
            IPersonBusinessManager personBusinessManager,
            ICompanyBusinessManager companyBusinessManager,
            IVendorBusinessManager vendorBusinessManager,
            ICategoryBusinessManager categoryBusinessManager) : base(logger, mapper) {
            _uccountBusinessManager = uccountBusinessManager;
            _personBusinessManager = personBusinessManager;
            _companyBusinessManager = companyBusinessManager;
            _vendorBusinessManager = vendorBusinessManager;
            _categoryBusinessManager = categoryBusinessManager;
        }

        public async Task<IActionResult> Index() {
            var vendors = await _vendorBusinessManager.GetVendors();
            ViewBag.Vendors = vendors.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() });

            var persons = await _personBusinessManager.GetPersons();
            var companies = await _companyBusinessManager.GetCompanies();
            //var stateGroups = Enum.GetNames(typeof(UccountTypes)).Select(x => new SelectListGroup() { Name = x }).ToList();

            ViewBag.Customers = persons.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() })
                .Union(companies.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }));

            var categories = await _categoryBusinessManager.GetCategories();
            ViewBag.Categories = categories.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name });

            var model = new UccountFilterViewModel();
            return View(model);
        }
    }
}

namespace Web.Controllers.Api {
    [Route("api/[controller]")]
    [ApiController]
    [LogAction]
    public class UccountController: ControllerBase {
        private readonly IMapper _mapper;
        private readonly IViewRenderService _viewRenderService;
        private readonly IUccountBusinessManager _uccountBusinessManager;
        private readonly ICompanyBusinessManager _companyBusinessManager;
        private readonly ICategoryBusinessManager _categoryBusinessManager;
        private readonly IVendorBusinessManager _vendorBusinessManager;
        private readonly IPersonBusinessManager _personBusinessManager;

        public UccountController(IMapper mapper, IViewRenderService viewRenderService,
            IUccountBusinessManager uccountBusinessManager,
            ICompanyBusinessManager companyBusinessManager,
            ICategoryBusinessManager categoryBusinessManager,
            IVendorBusinessManager vendorBusinessManager,
            IPersonBusinessManager personBusinessManager) {
            _mapper = mapper;
            _viewRenderService = viewRenderService;
            _uccountBusinessManager = uccountBusinessManager;
            _companyBusinessManager = companyBusinessManager;
            _categoryBusinessManager = categoryBusinessManager;
            _vendorBusinessManager = vendorBusinessManager;
            _personBusinessManager = personBusinessManager;
        }

        [HttpGet("GetUccounts", Name = "GetUccounts")]
        public async Task<PagerDto<UccountListViewModel>> GetUccounts([FromQuery] UccountFilterViewModel model) {
            var result = await _uccountBusinessManager.GetUccountPage(_mapper.Map<UccountFilterDto>(model, opts =>
                opts.AfterMap((_, dest) => (dest as UccountFilterDto).UserId = User.GetUserId())));
            var pager = new PagerDto<UccountListViewModel>(_mapper.Map<List<UccountListViewModel>>(result.Data), result.RecordsTotal, result.Start, result.PageSize);
            return pager;
        }

        [HttpGet("DetailsUccount", Name = "DetailsUccount")]
        public async Task<IActionResult> DetailsUccount([FromQuery] Guid id) {
            var item = await _uccountBusinessManager.GetUccount(id);
            if(item == null)
                return NotFound();

            var html = await _viewRenderService.RenderToStringAsync("_DetailsPartial", _mapper.Map<UccountViewModel>(item));
            return Ok(html);
        }

        [HttpGet("GetUccount", Name = "GetUccount")]
        public async Task<IActionResult> GetUccount([FromQuery] Guid id) {
            var item = await _uccountBusinessManager.GetUccount(id);
            if(item == null)
                return NotFound();

            return Ok(_mapper.Map<UccountViewModel>(item));
        }

        [HttpGet("GetUccountService", Name = "GetUccountService")]
        public async Task<IActionResult> GetUccountService([FromQuery] Guid id) {
            var item = await _uccountBusinessManager.GetService(id);
            if(item == null)
                return NotFound();

            return Ok(_mapper.Map<UccountServiceViewModel>(item));
        }

        [HttpGet("AddUccount", Name = "AddUccount")]
        public async Task<IActionResult> AddUccount([FromQuery] UccountTypes kind) {
            string html;
            var model = new UccountViewModel();
            var vendors = await _vendorBusinessManager.GetVendors();
            var categories = await _categoryBusinessManager.GetCategories();

            if(kind == UccountTypes.PERSONAL) {
                var persons = await _personBusinessManager.GetPersons();
                var viewDataDictionary = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary()) {
                    { "Vendors", vendors.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList() },
                    { "Persons", persons.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList() },
                    { "Categories", categories.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList() },
                    { "Kind", kind }
                };
                html = _viewRenderService.RenderToStringAsync("_CreatePartial", model, viewDataDictionary).Result;
            } else {
                var companies = await _companyBusinessManager.GetCompanies();
                var viewDataDictionary = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary()) {
                    { "Vendors", vendors.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList() },
                    { "Companies", companies.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList() },
                    { "Categories", categories.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList() },
                    { "Kind", kind }
                };
                html = _viewRenderService.RenderToStringAsync("_CreatePartial", model, viewDataDictionary).Result;
            }
            return Ok(html);
        }

        [HttpPost("CreateUccount", Name = "CreateUccount")]
        public async Task<IActionResult> CreateUccount([FromBody] UccountViewModel model) {
            try {
                if(ModelState.IsValid) {
                    var result = await _uccountBusinessManager.CreateUccount(_mapper.Map<UccountDto>(model));
                }
            } catch(Exception er) {
                return BadRequest(er.Message);
            }
            return Ok();
        }

        [HttpPut("UpdateUccount", Name = "UpdateUccount")]
        public async Task<IActionResult> UpdateUccount([FromQuery] Guid id, [FromBody] UccountViewModel model) {
            if(ModelState.IsValid) {
                var item = await _uccountBusinessManager.UpdateUccount(id, _mapper.Map<UccountDto>(model), User.GetUserId());
                if(item == null)
                    return BadRequest();
                return Ok(_mapper.Map<UccountViewModel>(item));
            }
            return BadRequest();
        }

        [HttpGet("EditUccount", Name = "EditUccount")]
        public async Task<IActionResult> EditUccount([FromQuery] Guid id) {
            var item = await _uccountBusinessManager.GetUccount(id);
            if(item == null)
                return NotFound();

            var mappedItem = _mapper.Map<UccountViewModel>(item);
            var persons = await _personBusinessManager.GetPersons();
            var companies = await _companyBusinessManager.GetCompanies();
            var vendors = await _vendorBusinessManager.GetVendors();
            var vendorCategories = await _vendorBusinessManager.GetVendorCategories(item.VendorId);
            var services = await _uccountBusinessManager.GetServices(id);
            var groupedServices = services
                .GroupBy(x => x.CategoryId)
                .Select(x => new UccountGroupedServiceViewModel() {
                    Id = Guid.NewGuid(),
                    Name = x.FirstOrDefault().Name,
                    CategoryId = x.FirstOrDefault().CategoryId,

Web/Views/Company/Create.cshtml
@model Web.ViewModels.CompanyGeneralViewModel

@{
    ViewData["Title"] = "Create Company";
    ViewData["SubTitle"] = "Please provide all required details to register new company";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index">Companies</a></li>
        <li class="breadcrumb-item active" aria-current="page">New</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" id="general-tab" href="#general">General</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <form id="submitForm" class="tab-content" method="POST" asp-action="Create">
            <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
                <div class="form-group row mb-3">
                    <div class="col-4">
                        <label asp-for="No"></label>
                        <input asp-for="No" class="form-control" required />
                        <span asp-validation-for="No" class="text-danger"></span>
                    </div>
                    <div class="col-8">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" required />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <div class="col-4">
                        <label asp-for="Website"></label>
                        <input asp-for="Website" class="form-control" placeholder="http://" />
                        <span asp-validation-for="Website" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <label asp-for="PhoneNumber"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <div class="col-4">
                        <label asp-for="CEO"></label>
                        <input asp-for="CEO" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="EIN"></label>
                        <input asp-for="EIN" class="form-control" />
                    </div>
                    <div class="col-3">
                        <label asp-for="DB"></label>
                        <input asp-for="DB" class="form-control" />
                    </div>
                    <div class="col-2">
                        <label asp-for="Founded"></label>
                        <input asp-for="Founded" type="date" class="form-control" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="card-footer">
        <div class="" role="toolbar" aria-label="Toolbar with button groups">
            <button type="submit" class="btn btn-outline-primary" form="submitForm">Save</button>
            <a asp-action="index" class="btn btn-link">Cancel</a>
        </div>
    </div>
</div>

Web/Views/Company/Edit.cshtml
@model Web.ViewModels.CompanyViewModel

@{
    ViewData["Title"] = "Edit Company";
    var guid = Guid.NewGuid();
    var sections = (List<Web.ViewModels.CompanySectionViewModel>)ViewBag.Sections;
}

@section RightSidebar {
    <div class="ui sticky">
        <div class="ui clearing">
            <h4 class="ui header">Sections</h4>
            <a asp-action="AddCompanySection" asp-route-id="@Model.Id" data-request="ajax" rel="dialog"><i class="plus icon"></i> Create</a>
        </div>
        <div id="sectionsContainer" class="ui vertical following fluid accordion text menu">
            @foreach(var section in sections) {
                <a class="item" href="#section_@(section.Id)">@(section.SectionName)</a>
            }
        </div>
    </div>
}

<div role="toolbar" class="ui secondary menu">
    <div class="right menu">
        <form asp-action="Delete" asp-route-Id="@Model.Id" method="delete" >
            <button type="submit" class="red ui button" onclick="if (!confirm('Are you sure want to delete this?')) { return false; }"><i class="trash icon"></i> Remove</button>
        </form>
    </div>
</div>

<div class="ui raised segment">
    <form id="@guid" class="ui form" asp-action="Edit" method="post">
        <fieldset>
            <h4 class="ui dividing header">General</h4>
            <input type="hidden" name="Id" value="@Model.Id" />
            <div class="two fields">
                <div class="field required">
                    <label asp-for="General.No"></label>
                    <input asp-for="General.No" name="No" required />
                    <span asp-validation-for="General.No"></span>
                </div>
                <div class="field required">
                    <label asp-for="General.Name"></label>
                    <input asp-for="General.Name" name="Name" required />
                    <span asp-validation-for="General.Name"></span>
                </div>
            </div>
            <div class="three fields">
                <div class="field">
                    <label asp-for="General.Website"></label>
                    <input asp-for="General.Website" name="Website" placeholder="http://" />
                    <span asp-validation-for="General.Website"></span>
                </div>
                <div class="field">
                    <label asp-for="General.PhoneNumber"></label>
                    <input asp-for="General.PhoneNumber" name="PhoneNumber" />
                    <span asp-validation-for="General.PhoneNumber"></span>
                </div>
                <div class="field">
                    <label asp-for="General.Email"></label>
                    <input asp-for="General.Email" name="Email" />
                    <span asp-validation-for="General.Email"></span>
                </div>
            </div>
            <div class="four fields">
                <div class="field">
                    <label asp-for="General.CEO"></label>
                    <input asp-for="General.CEO" name="CEO" />
                </div>
                <div class="field">
                    <label asp-for="General.EIN"></label>
                    <input asp-for="General.EIN" name="EIN" />
                </div>
                <div class="field">
                    <label asp-for="General.DB"></label>
                    <input asp-for="General.DB" name="DB" />
                    <span asp-validation-for="General.DB"></span>
                </div>
                <div class="field">
                    <label asp-for="General.Founded"></label>
                    <input asp-for="General.Founded" type="date" name="Founded" />
                </div>
            </div>
            <button type="submit" class="ui submit button">Save</button>
        </fieldset>
    </form>
</div>

<div id="cardContainer" class="ui cards">
    @foreach(var section in sections) {
    <div class="card" id="section_@(section.Id)">
        <div class="content">
            <form asp-action="DeleteCompanySection" asp-route-id="@(section.Id)" data-request="ajax" rel="deleteCompanySectionComplete" method="delete">
                <button class="mini ui icon button right floated" onclick="if (!confirm('Are you sure want to delete this?')) { return false; }"><i class="close icon"></i></button>
            </form>
            <div class="header">@(section.SectionName)</div>
            <div class="meta">@(section.SectionDescription)</div>
            <div class="description">
                <p></p>
            </div>
        </div>
        <a class="ui bottom attached button" asp-action="AddCompanySectionField" asp-route-id="@(section.Id)" data-request="ajax" rel="dialog">
            <i class="add icon"></i> Add
        </a>
    </div>
    }
</div>

@section Scripts {
    <script type="text/javascript">
        function createCompanySectionComplete(jqXHR, status) {
            if (status === 'success') {
                var data = jqXHR.responseJSON;
                $('#sectionsContainer').append(`<a class='item' href='#${data.sectionCode}'>${data.sectionName}</a>`);
                $('#cardContainer').append(``);
                $('.modal').modal('hide');
            }
        }

        function deleteCompanySectionComplete(jqXHR, status) {
            if (status === 'success') {
                var data = jqXHR.responseJSON;
                $(`#section_${data}`).remove();
            }
        }

        $(document).ready(function () {

        });
    </script>
}

Web/Views/Company/_AddCompanyDataPartial.cshtml
@model CompanyDataListViewModel
@{
    var formId = Guid.NewGuid();

    var servicesUrl = Url.Action("GetUccount", "Uccount");
    var dataUrl = Url.Action("GetUccountService", "Uccount");

    var accounts = (SelectListItem[])ViewData["Accounts"];
}

<form id="@formId" class="ui form" asp-route="CreateCompanyData" method="post" data-request="ajax" rel="onCreateCompanyDataSubmit">
    <input type="hidden" asp-for="CompanyId" />
    <div class="ui horizontal segments">
        <div class="ui segment four wide" style="max-width: 20rem;">
            <h4>Accounts</h4>
            <div id="@(formId)_accounts" class="ui secondary vertical menu" style="width: auto;">
                @for(int i = 0; i < accounts.Count(); i++) {
                    <div class="item" data-value="@accounts[i].Value">
                        @accounts[i].Text
                    </div>
                }
            </div>
        </div>
        <div class="ui segment four wide" style="max-width: 25rem;">
            <h4>Services</h4>
            <div id="@(formId)_services" class="ui secondary vertical menu" style="width: auto;">
            </div>
        </div>
        <div class="ui segment twelve wide">
            <h4>Data</h4>
            <div id="@(formId)_data" class="ui secondary vertical menu" style="width: auto;">
            </div>
        </div>
    </div>
    <div id="@(formId)_hidden_data">
    </div>
</form>


<script type="text/javascript">
    $(document).ready(function () {
        let lastActiveAccount = $('#@(formId)_accounts').find('.active');
        let lastActiveService = $('#@(formId)_services').find('.active');

        let getHtmlChildren = function (items) {
            return $(items.map((item) => (
                `<div class="item" data-value="${item.id}">
                    ${item.name}${item.value ? ': ' + item.value : ''}
                </div>`
            )).join("\n "));
        }

        $('#@(formId)_accounts').on("click", "div", function () {
            lastActiveAccount.removeClass('active');
            $(this).addClass('active');
            lastActiveAccount = $(this);

            $.get('@servicesUrl', { 'id': $(this).data('value') }).done(result => {
                $('#@(formId)_services').html(getHtmlChildren(result.services));
                $('#@(formId)_data').html('');
                $(`#@(formId)_hidden_data`).html('');
            });
        });
        $('#@(formId)_services').on("click", "div", function () {
            lastActiveService.removeClass('active');
            $(this).addClass('active');
            lastActiveService = $(this);

            $.get('@dataUrl', { 'id': $(this).data('value') }).done(result => {
                $('#@(formId)_data').html(getHtmlChildren(result.fields));
                $(`#@(formId)_hidden_data`).html('');
            });
        });
        $('#@(formId)_data').on("click", "div", function () {
            if ($(this).hasClass('active')) {
                $(`#${$(this).data('value')}`).remove();

                $(this).removeClass('active');
            }
            else {
                $('#@(formId)_hidden_data').append(`
                    <div id="${$(this).data('value')}">
                        <input type="hidden" name="Data[][FieldId]" value="${$(this).data('value')}" />
                        <input type="hidden" name="Data[][CompanyId]" value="@Model.CompanyId" />
                    </div>`);

                $(this).addClass('active');
            }
        });
    });
</script>

Web/Views/Company/_CreatePartial.cshtml
@model Web.ViewModels.CompanyViewModel

@{
    var guid = Guid.NewGuid();
    var serviceFieldsGuid = Guid.NewGuid();

    var persons = (List<SelectListItem>)ViewData["Persons"];
    var categories = (List<SelectListItem>)ViewData["Categories"];
}

<form id="@guid" class="ui form" asp-route="CreateCompany" method="post" data-request="ajax">
    <fieldset>
        <h4 class="ui dividing header">General</h4>
        <input type="hidden" name="Id" value="@Model.Id" />
        <div class="fields">
            <div class="twelve wide field required">
                <label asp-for="Name"></label>
                <input asp-for="Name" required data-value-type="string" />
            </div>

            <div class="four wide field required">
                <label asp-for="CEOId"></label>
                <select id="companies-select" class="ui search dropdown" required selected="false" asp-for="CEOId" asp-items="@persons">
                    <option value="" selected disabled hidden></option>
                </select>
            </div>
        </div>

        <div class="three fields">
            <div class="field required">
                <label asp-for="EIN"></label>
                <input asp-for="EIN" data-value-type="string" required />
            </div>
            <div class="field required">
                <label asp-for="DB"></label>
                <input asp-for="DB" data-value-type="string" required />
                <span asp-validation-for="DB"></span>
            </div>
            <div class="field">
                <label asp-for="Founded"></label>
                <input asp-for="Founded" type="date" data-value-type="string" />
            </div>
        </div>
        <div class="field">
            <label asp-for="Description">Description <span class="text-muted">(Optional)</span></label>
            <textarea asp-for="Description" rows="3" data-value-type="string"></textarea>
        </div>
        <div class="ui right floated dropdown mini icon button" tabindex="0" >
            <i class="plus icon"></i>
            <div class="menu">
                @foreach(var category in categories) {
                    <a data-request="ajax" id="@category.Value" class="item" data-target="#@serviceFieldsGuid" rel="onSectionCreateClick" asp-route="GetCategory" asp-route-id="@category.Value">@category.Text</a>
                }
            </div>
        </div>

        <h4 class="ui dividing header">Fields</h4>

        <div id="@serviceFieldsGuid"></div>
    </fieldset>
</form>